import React, { useEffect, useState } from "react";
import axios from "axios";
import { Link, useNavigate } from "react-router-dom";
import { MdDelete, } from "react-icons/md";
import { FaEdit } from "react-icons/fa";
import toast from "react-hot-toast";
import Aside from "../ui/Aside-content";

function Report() {
    const [reports, setReports] = useState([]);
    const navigate = useNavigate();

    async function fetchReport() {
        const res = await axios.get("https://meeting-scheduler-system-server.vercel.app/get-all-report");
        // console.log(res.data)
        setReports(res.data.report);
    }

    useEffect(() => {
        fetchReport();
    }, []);

    async function deleteReport(id) {
        try {
            await axios.delete(`https://meeting-scheduler-system-server.vercel.app/delete-report${id}`);

            setReports(prev => prev.filter(r => r._id !== id));
            toast.success("Report deleted successfully");
        } catch (error) {
            toast.error(error.response?.data?.msg || "Network error, please try later!");
        }
    }

    return (
        <>
            <Aside />
            <div className="min-h-screen  w-[77%] absolute top-0 right-0 bg-gradient-to-br from-gray-900 via-black to-gray-900 flex">


                <main className="flex-1 p-12">
                    <h3 className="text-3xl font-bold text-white">All Reports</h3>

                    <div className="mt-6 overflow-x-auto bg-gray-800/80 border border-gray-700 rounded-xl shadow-xl">
                        <table className="w-full text-sm text-left text-gray-300">
                            <thead className="bg-gray-900 text-gray-400 uppercase text-xs">
                                <tr>
                                    <th className="px-6 py-4">Title</th>
                                    <th className="px-6 py-4">Generated By</th>
                                    <th className="px-6 py-4">Date</th>
                                    <th className="px-6 py-4">Total Users</th>
                                    <th className="px-6 py-4">Type</th>
                                    <th className="px-6 py-4">Actions</th>
                                </tr>
                            </thead>

                            <tbody>
                                {Array.isArray(reports) && reports.map(m => (
                                    <tr key={m._id} className="border-b border-gray-700 hover:bg-gray-700/40">
                                        <td className="px-6 py-4 font-medium text-white">{m.reportTitle}</td>
                                        <td className="px-6 py-4">{m.reportGenerate}</td>
                                        <td className="px-6 py-4">{m.date}</td>
                                        <td className="px-6 py-4">{m.totalUser}</td>
                                        <td className="px-6 py-4">{m.reportType}</td>
                                        <td className="px-6 py-4 flex justify-end gap-4">
                                            <div className="flex mt-3 gap-3">
                                                <FaEdit
                                                    onClick={() => navigate(`/edit-report/${m._id}`)}
                                                    className="text-xl text-indigo-400 hover:text-indigo-300 cursor-pointer"
                                                />
                                                <MdDelete
                                                    onClick={() => deleteReport(m._id)}
                                                    className="text-xl text-indigo-400 hover:text-red-400 cursor-pointer"
                                                />
                                            </div>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </main>
            </div>
        </>
    );
}

export default Report;

